package msg

const (
	AUTH_SESSION_START        = 600
	AUTH_SESSION_HS1          = 601
	AUTH_SESSION_INCOMING_HS1 = 602
	AUTH_SESSION_HS2          = 603
	AUTH_SESSION_INCOMING_HS2 = 604
	AUTH_LAYER_ENCRYPT        = 605
	AUTH_LAYER_ENCRYPT_RESP   = 606
	AUTH_LAYER_DECRYPT        = 607
	AUTH_LAYER_DECRYPT_RESP   = 608
	AUTH_SESSION_CLOSE        = 609
	// Reserved up to 649.
)
